version: '3.3'

volumes:
  postgres:

services:
  db:
    image: postgres:10
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kaifbreaker_development
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]

  server_app: &server_app
    build: .
    command: bundle exec rails server -b 0.0.0.0
    entrypoint: "./docker-entrypoint.sh"
    volumes:
      - .:/home/www/kaifbreaker
    tty: true
    stdin_open: true
    restart: on-failure
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: kaifbreaker_development
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      SECRET_KEY_BASE: 1970376485e92011aca6a66efd1e9f4103f5d583d556fa3f31fe176f72fd1f1aef87a9c97ce7be87f1e3f39e99813f966a3e94e72ab79370eac0c9933ec42800
    depends_on:
      - db
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
